version: '3.9'

volumes:
  postgres-data: {}

services:
  metabase:
    image: metabase:v0.55.8.6
    hostname: metabase
    restart: unless-stopped
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USER:-dbuser}
      MB_DB_PASS: ${DB_PASS:-pass}
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-dbuser}
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge
